"use client";

import { useState, Suspense } from "react";
import { useSocket } from "@/hooks/useSocket";
import JoinModal from "@/components/JoinModal";
import Timer from "@/components/Timer";
import SentenceDisplay from "@/components/SentenceDisplay";
import TypingInput from "@/components/TypingInput";
import StatsBar from "@/components/StatsBar";
import PlayerTable from "@/components/PlayerTable";

function GameContent() {
  const { connected, gameState, timeLeft, myStats, error, joinGame, sendProgress } =
    useSocket();
  const [joined, setJoined] = useState(false);
  const [input, setInput] = useState("");
  const [finished, setFinished] = useState(false);
  const [myName, setMyName] = useState("");

  const handleJoin = (name: string) => {
    joinGame(name);
    setJoined(true);
    setMyName(name);
  };

  const handleInput = (val: string) => {
    if (!gameState || gameState.status !== "playing" || finished) return;
    setInput(val);
    sendProgress(val);

    if (val.trim() === gameState.round.sentence.trim()) {
      setFinished(true);
    }
  };

  const currentRound = gameState?.round.roundNumber;
  const [lastRound, setLastRound] = useState(0);
  if (currentRound && currentRound !== lastRound) {
    if (lastRound !== 0) {
      setInput("");
      setFinished(false);
    }
    setLastRound(currentRound);
  }

  //Generated by AI

  if (!connected) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <p className="text-gray-400">Connecting...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <div className="bg-gray-800 rounded p-6 text-center">
          <p className="text-red-400 mb-2">Connection failed</p>
          <p className="text-gray-400 text-sm">{error}</p>
        </div>
      </div>
    );
  }

  if (!gameState) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <p className="text-gray-400">Loading...</p>
      </div>
    );
  }

  const myPlayer = gameState.players.find((p) => p.name === myName);
  const myWpm = myPlayer?.wpm ?? 0;
  const myAccuracy = myPlayer?.accuracy ?? 1;

  return (
    <>
      {!joined && <JoinModal onJoin={handleJoin} />}

      <div className="min-h-screen bg-gray-900 text-white p-6">
        <div className="max-w-4xl mx-auto">

        
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-2xl font-bold text-white">Adrian Tanski</h1>
              
            </div>
            <Timer
              timeLeftMs={timeLeft}
              status={gameState.status}
              roundNumber={gameState.round.roundNumber}
            />
          </div>

        
          {joined && (
            <div className="mb-6">
              <StatsBar wpm={myWpm} accuracy={myAccuracy} savedStats={myStats} />
            </div>
          )}

          
          <div className="mb-4">
            <SentenceDisplay
              sentence={gameState.round.sentence}
              userInput={input}
            />
          </div>

         
          {joined && (
            <div className="mb-8">
              <TypingInput
                value={input}
                onChange={handleInput}
                disabled={gameState.status !== "playing" || !joined}
                finished={finished}
              />
            </div>
          )}

       
          {gameState.status === "between_rounds" && (
            <div className="mb-6 bg-gray-800 rounded p-4 text-center">
              <p className="text-yellow-400 text-sm">
                Round {gameState.round.roundNumber} ended - next round starting soon
              </p>
            </div>
          )}

          
          <div>
            <h2 className="text-lg font-semibold text-gray-300 mb-3">
              Leaderboard
            </h2>
            <PlayerTable
              players={gameState.players}
              sentence={gameState.round.sentence}
            />
          </div>
        </div>
      </div>
    </>
  );
}

export default function Home() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-gray-900 flex items-center justify-center">
          <p className="text-gray-400">Loading...</p>
        </div>
      }
    >
      <GameContent />
    </Suspense>
  );
}