"use client";

interface Props {
  timeLeftMs: number;
  status: "waiting" | "playing" | "between_rounds";
  roundNumber: number;
}
//THIS WAS GENERATED BY AI TO SAVE TIME
export default function Timer({ timeLeftMs, status, roundNumber }: Props) {
  const seconds = Math.ceil(timeLeftMs / 1000);

  return (
    <div className="flex items-center gap-3">
      <span className="text-sm text-gray-400">Round {roundNumber}</span>
      <span className={`text-2xl font-mono font-bold ${
        seconds <= 5 && status === "playing" ? "text-red-400" : "text-green-400"
      }`}>
        {seconds}s
      </span>
      <span className="text-sm text-gray-500">
        {status === "playing" ? "left" : status === "between_rounds" ? "next round" : "waiting"}
      </span>
    </div>
  );
}